spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 9191